### PR TITLE
Update camunda chart092022

### PR DESCRIPTION
**Pull request by LockeBirdsey**
Bump up the chart to match latest and then follow-up with a bump to 8.0.6

### CODE REVIEW

**Comment by LockeBirdsey** [comment]
file of most interest is charts/camunda-platform/values.yaml

**Comment by LockeBirdsey** [comment]
they now have an ingress option for the gateway, disabled by default. I wonder if there's any use in this for us

**Review by remware — APPROVED** [review]

**Comment by remware** [comment]
I wonder if we need the part for OpenShift ?

**Comment by LockeBirdsey** [comment]
> I wonder if we need the part for OpenShift ?

No we dont. I just haven't gotten around to removing it yet.

**Pull request merged**
