### PR TITLE
Update from upstream

### PR DESCRIPTION
**Pull request by Ninjaluo**
### Checklist

Please make sure to follow our [Contributing Guide](../blob/main/CONTRIBUTING.md).

**Before opening the PR:**

- [ ] There is no other open [pull request](../pulls) for the same update/change.
- [ ] The commits follow our [Commit Guidelines](../blob/main/CONTRIBUTING.md#commit-guidelines).
- [ ] Tests for charts are added.
- [ ] The main Helm chart and sub-chart are updated (if needed).
- [ ] In-repo [documentation](../blob/main/CONTRIBUTING.md#documentation) are updated (if needed).

**After opening the PR:**

- [ ] Did you sign our CLA (Contributor License Agreement)? It will show once you open the PR.
- [ ] Did all checks/tests pass in the PR?

### CODE REVIEW

**Review by jaatiain — APPROVED** [review]
Do we still need this fork. Could we just configure the main community branch.


So many changes only way to verify this is use it.

**Comment by LockeBirdsey** [comment]
> Do we still need this fork. Could we just configure the main community branch.
> 
> So many changes only way to verify this is use it.

thats not a bad idea. we have one addition that we needed because KaaS wouldn't run the pods properly (some security context thing if I remember correctly). Maybe we should doing that

**Comment by jaatiain** [comment]
> > Do we still need this fork. Could we just configure the main community branch.
> > So many changes only way to verify this is use it.
> 
> thats not a bad idea. we have one addition that we needed because KaaS wouldn't run the pods properly (some security context thing if I remember correctly). Maybe we should doing that

was it this?

@@ -1,5 +1,5 @@
{{ if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "zeebe.names.broker" . }}

**Comment by LockeBirdsey** [comment]
> > > Do we still need this fork. Could we just configure the main community branch.
> > > So many changes only way to verify this is use it.
> > 
> > 
> > thats not a bad idea. we have one addition that we needed because KaaS wouldn't run the pods properly (some security context thing if I remember correctly). Maybe we should doing that
> 
> was it this?
> 
> @@ -1,5 +1,5 @@ {{ if .Values.podDisruptionBudget.enabled }} apiVersion: policy/v1beta1 apiVersion: policy/v1 kind: PodDisruptionBudget metadata: name: {{ include "zeebe.names.broker" . }}
> 
> Now there is policy/v1

nah it was https://github.com/elisapolystar/camunda-cloud-helm/commit/1dcbe368fc3f7b07102297a48b38ef2bc0f26c31

**Comment by jaatiain** [comment]
> > > > Do we still need this fork. Could we just configure the main community branch.
> > > > So many changes only way to verify this is use it.
> > > 
> > > 
> > > thats not a bad idea. we have one addition that we needed because KaaS wouldn't run the pods properly (some security context thing if I remember correctly). Maybe we should doing that
> > 
> > 
> > was it this?
> > @@ -1,5 +1,5 @@ {{ if .Values.podDisruptionBudget.enabled }} apiVersion: policy/v1beta1 apiVersion: policy/v1 kind: PodDisruptionBudget metadata: name: {{ include "zeebe.names.broker" . }}
> > Now there is policy/v1
> 
> nah it was [1dcbe36](https://github.com/elisapolystar/camunda-cloud-helm/commit/1dcbe368fc3f7b07102297a48b38ef2bc0f26c31)

ok, maybe we could make a free fork and add it there, and create a PR for the main community branch.

**Comment by LockeBirdsey** [comment]
> > > > > Do we still need this fork. Could we just configure the main community branch.
> > > > > So many changes only way to verify this is use it.
> > > > 
> > > > 
> > > > thats not a bad idea. we have one addition that we needed because KaaS wouldn't run the pods properly (some security context thing if I remember correctly). Maybe we should doing that
> > > 
> > > 
> > > was it this?
> > > @@ -1,5 +1,5 @@ {{ if .Values.podDisruptionBudget.enabled }} apiVersion: policy/v1beta1 apiVersion: policy/v1 kind: PodDisruptionBudget metadata: name: {{ include "zeebe.names.broker" . }}
> > > Now there is policy/v1
> > 
> > 
> > nah it was [1dcbe36](https://github.com/elisapolystar/camunda-cloud-helm/commit/1dcbe368fc3f7b07102297a48b38ef2bc0f26c31)
> 
> ok, maybe we could make a fresh fork and add it there, and create a PR for the main community branch.

yeah that might not be a bad idea, then we wouldn't have to deal with this all the time 😅

**Comment by LockeBirdsey** [comment]
> > > > > Do we still need this fork. Could we just configure the main community branch.
> > > > > So many changes only way to verify this is use it.
> > > > 
> > > > 
> > > > thats not a bad idea. we have one addition that we needed because KaaS wouldn't run the pods properly (some security context thing if I remember correctly). Maybe we should doing that
> > > 
> > > 
> > > was it this?
> > > @@ -1,5 +1,5 @@ {{ if .Values.podDisruptionBudget.enabled }} apiVersion: policy/v1beta1 apiVersion: policy/v1 kind: PodDisruptionBudget metadata: name: {{ include "zeebe.names.broker" . }}
> > > Now there is policy/v1
> > 
> > 
> > nah it was [1dcbe36](https://github.com/elisapolystar/camunda-cloud-helm/commit/1dcbe368fc3f7b07102297a48b38ef2bc0f26c31)
> 
> ok, maybe we could make a fresh fork and add it there, and create a PR for the main community branch.

yeah that might not be a bad idea, then we wouldn't have to deal with this all the time 😅

**Comment by LockeBirdsey** [comment]
> > > > > Do we still need this fork. Could we just configure the main community branch.
> > > > > So many changes only way to verify this is use it.
> > > > 
> > > > 
> > > > thats not a bad idea. we have one addition that we needed because KaaS wouldn't run the pods properly (some security context thing if I remember correctly). Maybe we should doing that
> > > 
> > > 
> > > was it this?
> > > @@ -1,5 +1,5 @@ {{ if .Values.podDisruptionBudget.enabled }} apiVersion: policy/v1beta1 apiVersion: policy/v1 kind: PodDisruptionBudget metadata: name: {{ include "zeebe.names.broker" . }}
> > > Now there is policy/v1
> > 
> > 
> > nah it was [1dcbe36](https://github.com/elisapolystar/camunda-cloud-helm/commit/1dcbe368fc3f7b07102297a48b38ef2bc0f26c31)
> 
> ok, maybe we could make a fresh fork and add it there, and create a PR for the main community branch.

yeah that might not be a bad idea, then we wouldn't have to deal with this all the time 😅

**Comment by LockeBirdsey** [comment]
> > > > > Do we still need this fork. Could we just configure the main community branch.
> > > > > So many changes only way to verify this is use it.
> > > > 
> > > > 
> > > > thats not a bad idea. we have one addition that we needed because KaaS wouldn't run the pods properly (some security context thing if I remember correctly). Maybe we should doing that
> > > 
> > > 
> > > was it this?
> > > @@ -1,5 +1,5 @@ {{ if .Values.podDisruptionBudget.enabled }} apiVersion: policy/v1beta1 apiVersion: policy/v1 kind: PodDisruptionBudget metadata: name: {{ include "zeebe.names.broker" . }}
> > > Now there is policy/v1
> > 
> > 
> > nah it was [1dcbe36](https://github.com/elisapolystar/camunda-cloud-helm/commit/1dcbe368fc3f7b07102297a48b38ef2bc0f26c31)
> 
> ok, maybe we could make a fresh fork and add it there, and create a PR for the main community branch.

yeah that might not be a bad idea, then we wouldn't have to deal with this all the time 😅

**Comment by LockeBirdsey** [comment]
> > > > > Do we still need this fork. Could we just configure the main community branch.
> > > > > So many changes only way to verify this is use it.
> > > > 
> > > > 
> > > > thats not a bad idea. we have one addition that we needed because KaaS wouldn't run the pods properly (some security context thing if I remember correctly). Maybe we should doing that
> > > 
> > > 
> > > was it this?
> > > @@ -1,5 +1,5 @@ {{ if .Values.podDisruptionBudget.enabled }} apiVersion: policy/v1beta1 apiVersion: policy/v1 kind: PodDisruptionBudget metadata: name: {{ include "zeebe.names.broker" . }}
> > > Now there is policy/v1
> > 
> > 
> > nah it was [1dcbe36](https://github.com/elisapolystar/camunda-cloud-helm/commit/1dcbe368fc3f7b07102297a48b38ef2bc0f26c31)
> 
> ok, maybe we could make a fresh fork and add it there, and create a PR for the main community branch.

yeah that might not be a bad idea, then we wouldn't have to deal with this all the time 😅

**Comment by LockeBirdsey** [comment]
> > > > > Do we still need this fork. Could we just configure the main community branch.
> > > > > So many changes only way to verify this is use it.
> > > > 
> > > > 
> > > > thats not a bad idea. we have one addition that we needed because KaaS wouldn't run the pods properly (some security context thing if I remember correctly). Maybe we should doing that
> > > 
> > > 
> > > was it this?
> > > @@ -1,5 +1,5 @@ {{ if .Values.podDisruptionBudget.enabled }} apiVersion: policy/v1beta1 apiVersion: policy/v1 kind: PodDisruptionBudget metadata: name: {{ include "zeebe.names.broker" . }}
> > > Now there is policy/v1
> > 
> > 
> > nah it was [1dcbe36](https://github.com/elisapolystar/camunda-cloud-helm/commit/1dcbe368fc3f7b07102297a48b38ef2bc0f26c31)
> 
> ok, maybe we could make a fresh fork and add it there, and create a PR for the main community branch.

yeah that might not be a bad idea, then we wouldn't have to deal with this all the time 😅

**Comment by LockeBirdsey** [comment]
oh boy that git outage just caused my comment to send multiple times huh

**Pull request merged**
